[pytest]
filterwarnings =
    ignore::DeprecationWarning:sqlalchemy.*
    ignore::RuntimeWarning
asyncio_mode = strict
markers =
    asyncio: mark test as asyncio-based
addopts = -v --cov=src --cov-report=xml
