"""create weather_requests table

Revision ID: 72df5a15cf2f
Revises:
Create Date: 2026-07-10 12:23:36.396542

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72df5a15cf2f"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "weather_requests",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("temp_c", sa.Float(), nullable=True),
        sa.Column("condition", sa.String(length=100), nullable=True),
        sa.Column("success", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("weather_requests")
    # ### end Alembic commands ###
